.IGNORE: all clean

FLAGS=-DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++17 

all:
	g++ $(FLAGS) hw0401.cpp -o hw0401
	g++ $(FLAGS) hw0402.cpp -o hw0402
	g++ $(FLAGS) hw0403.cpp -o hw0403
	g++ $(FLAGS) hw0404.cpp -o hw0404
	
clean:
	rm hw0?0?