.IGNORE: all clean

FLAGS=-DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++17 

all:
	g++ $(FLAGS) hw0101.cpp -o hw0101
	g++ $(FLAGS) hw0102.cpp -o hw0102
	g++ $(FLAGS) hw0103.cpp -o hw0103
	g++ $(FLAGS) hw0104.cpp -o hw0104
	
clean:
	rm hw0?0?