.IGNORE: all clean

FLAGS=-DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++17 

all:
	g++ $(FLAGS) hw0201.cpp -o hw0201
	g++ $(FLAGS) hw0202.cpp -o hw0202
	g++ $(FLAGS) hw0203.cpp -o hw0203
	g++ $(FLAGS) hw0204.cpp -o hw0204
	g++ $(FLAGS) bonus.cpp -o bonus
	
clean:
	rm hw0?0? bonus