.IGNORE : all clean

all:
	gcc hw0301.c -o hw0301
	gcc hw0302.c -o hw0302
	gcc hw0303.c -o hw0303
	gcc hw0304.c -o hw0304
	# gcc hw0305.c -o hw0305
	
clean:
	rm *.o hw0?0? *.zip bonus
	
zip:
	zip -r hw03.zip *