.IGNORE : all clean

all:
	gcc hw0101.c -o hw0101
	gcc hw0102.c -o hw0102
	gcc hw0103.c -o hw0103
	gcc hw0104.c -o hw0104

clean:
	rm *.o hw010? *.zip
	
zip:
	zip -r hw01.zip *.c Makefile README.md *.pdf