.IGNORE : all clean

all:
	gcc hw0401.c -o hw0401 -lm
	gcc hw0402.c -o hw0402 -lm
	gcc hw0403.c -o hw0403 -lm
	gcc hw0404.c -o hw0404 -lm
	
clean:
	rm *.o hw0?0? *.zip bonus maldives_*.bmp
	
zip:
	zip -r hw04.zip *