.IGNORE : all clean

all:
	gcc hw0301.c -o hw0301 -lm
	gcc hw0302.c -o hw0302 -lm
	gcc hw0303.c -o hw0303
	gcc hw0304.c -o hw0304
	gcc hw0305.c -o hw0305

clean:
	rm *.o hw030?

zip:
	zip -r hw03.zip *c Makefile README.md *.pdf