.IGNORE: all clean

FLAGS=-DONLINE_JUDGE -O2 -w -fmax-errors=3 -std=c++17 

all:
	g++ $(FLAGS) hw0301.cpp -o hw0301
	g++ $(FLAGS) hw0302.cpp -o hw0302
	g++ $(FLAGS) hw0303.cpp -o hw0303
	g++ $(FLAGS) hw0304.cpp -o hw0304
	
clean:
	rm hw0?0?